finitestatemachine/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from statemachine import views
from statemachine.views import Login
from statemachine.middlewares.cant_login_after_login import cantLoginAfterLogin
from statemachine.middlewares.login_req_middleware import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^_nested_admin/', include('nested_admin.urls')),
    path("signup/", cantLoginAfterLogin(views.signup)),
    path("login/", cantLoginAfterLogin(Login.as_view())),
    path("profile/", login_required(views.profile)),
    path("profile/profile_update/", login_required(views.profile_update)),
    path("logout/", views.logout),
    path("office/", views.office),
    path("office/<int:workflow_id>/start", login_required(views.workflow_start)),
    path("office/<int:workflow_id>/submit", login_required(views.workflow_submit)),
    path("state/<int:state_id>/previous/", views.previous),
    path("office/<int:workflow_id>/review", views.review, name="review"),
    path("office/<int:workflow_id>/doctor", views.doctor),
    path("", views.home),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

statemachine/models.py
from django.contrib.auth.models import User
from django.db import models

from statemachine.enums import QuestionType


class Workflow(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=32)
    condition = models.CharField(max_length=32, blank=True, null=True)
    initial_state = models.BooleanField(default=False)
    workflow = models.ForeignKey(Workflow, on_delete=models.CASCADE)
    next_states = models.ManyToManyField('self', through='StateNextStates', symmetrical=False)
    terminal_state = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def validate(self, user_response):
        print(user_response)
        print(self.condition)
        if self.condition:
            return self.condition.lower() == user_response.lower()
        return True


class StateNextStates(models.Model):

    class Meta:
        ordering = ('priority_order',)

    state = models.ForeignKey(State, on_delete=models.CASCADE, related_name='state_id')
    next_state = models.ForeignKey(State, on_delete=models.CASCADE, related_name='next_state')
    priority_order = models.PositiveIntegerField(default=0)


class Question(models.Model):
    question_type = models.IntegerField(choices=QuestionType.choices(), db_column='type', default=int(QuestionType.radio))
    question_text = models.CharField(max_length=100)
    state = models.ForeignKey(State, on_delete=models.CASCADE, related_name='questions')


class Option(models.Model):
    value = models.CharField(max_length=32)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='options')


class User(models.Model):
    name = models.CharField(max_length=41)
    mobileNo = models.CharField(max_length=10)
    email = models.EmailField(max_length=20)
    pwd = models.CharField(max_length=10)
    image = models.ImageField(upload_to='upload/images', blank=True)
    address = models.CharField(max_length=100)


class UserState(models.Model):
    user_id = models.PositiveIntegerField()
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    workflow_id = models.PositiveIntegerField()
    pre_state_id = models.PositiveIntegerField(null=True, blank=True)
    option_id = models.PositiveIntegerField(null=True)


class UserStateMapping(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>


    {% load static %}
    <link rel="stylesheet" href="{% static '/css/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/all.min.css' %}">


    <style>
        body{
        background-color: white;
        background-repeat: no-repeat;
        background-size: 100%;
        }


    </style>
</head>
<body>
<form action="/base">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/office/" style="color:white;"><h2>My Health</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                   <h3> <a class="nav-link" href="/"> Home <span class="sr-only">(current)</span></a></h3>
                </li>

            </ul>

            <ul class="navbar-nav ml-auto">
                {% if request.session.user %}
                <a style="color:teal;"><h2> Hello, </h2> <a style="color:yellow;"><h2> {{request.session.user.name}} </h2>
                </a> </a>

                <li class="nav-item active">
                    <h3><a class="nav-link" href="/profile">Profile <i class="fas fa-info-circle"></i></a></h3>
                </li>


                <li class="nav-item active">
                   <h3> <a class="nav-link" href="/logout">Logout <i class="fas fa-sign-out-alt"></i></a></h3>
                </li>
                {% else %}
                <li class="nav-item active">
                   <h3> <a class="nav-link" href="/login">Login <i class="fas fa-sign-in-alt"></i></a></h3>
                </li>
                <li class="nav-item active">
                    <h3><a class="nav-link" href="/signup">SignUp <i class="fas fa-user-plus"></i></a></h3>
                </li>
                {% endif %}
            </ul>

        </div>
    </nav>
</form>
{% block content %}


{% endblock %}

{% load static %}

<script src="{% static '/js/all.min.js' %}"> </script>

</body>
</html>

templates/doctor.html
{% extends "base.html" %}

{% block content %}
<div class="ui form" xmlns="http://www.w3.org/1999/html">
    <div class="container mt-4">
        <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
            <h1>Doctor's Review On Patient Condition </h1>
            <form action="/doctor/">
                {% if user %}
                <h3 style="color:tomato">Patient Name: &nbsp;&nbsp;{{user.name}}</h3>
                {% if state %}
                <h3 style="color:teal">Patient's Issue: &nbsp;&nbsp;{{state.workflow}}</h3>
                     <br>
                {% endif %}

                <table border="5">
                    <thead>
                    <tr>
                        <th style="font-size:18px; color:blue;"> Question</th>
                        <th style="font-size:18px; color:blue;"> User Response</th>
                    </tr>
                    </thead>
                    {% for res in responses %}
                    <tbody>
                    <tr>
                        <td style="font-size:18px; color:black;">{{res.question_text}}</td>
                        <td style="font-size:18px; color:maroon;">{{res.answer}}</td>
                    </tr>
                    </tbody>
                    {% endfor %}
                    {% endif %}

                </table>
                <br>
                <br>
                <button class="btn btn-warning">use this medication</a></button>&nbsp;&nbsp;&nbsp;&nbsp;
                <button class="btn btn-danger">Need following test reports</a></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}


{% block content %}

    <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
<div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">My Health App
      </h1>

  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center" align="center">
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
      <img class="object-cover mx-auto object-center rounded" alt="hero" src="https://source.unsplash.com/720x600/?health">
    </div>

  </div>
     </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
        <h1 class="display-6"> LoginForm </h1>
        <br>
        <form class="ui form" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button  type="submit" class="btn btn-primary">Login</button>
            <h3> New User? Please Signup Here</h3>

            <a href="/signup" class="btn btn-warning">Signup</a>
        </form>
    </div>
</div>
{% endblock %}

templates/office.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/label.css' %}">
<div class="ui form" xmlns="http://www.w3.org/1999/html">
    <div class="container mt-4">
        <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
            <ul>

                {% if workflow %}
                {% for wrkfl in workflow %}
                <h2>

                        <button class="btn btn-danger"><a style="color:white;" href="{{ wrkfl.id }}/review"> review </a>
                        </button>

                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <label>
                    <a style="color:teal;" href="{{ wrkfl.id }}/start"> {{ wrkfl }} </a>
                        </label>
                </h2>
                {% endfor %}
                {% endif %}

            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}


{% block content %}
<div class="ui form">
    <div class="container mt-4">
        <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
            <h1 class="display-6" align="center" style="color:teal;"> Profile </h1>
            <br>
            <form class="ui form" method="post">
                <ul>

                    {% if user %}
                   <h3>name:<input type="text" value="{{user.name}}" style="color:brown" readonly></h3>
                   <h3>mobile:<input type="text" value="{{user.mobileNo}}" style="color:brown" readonly></h3>
                   <h3>email:<input type="text" value="{{user.email}}" style="color:brown" readonly></h3>
                    <h3>password:<input type="text" value="{{user.pwd}}" style="color:brown" readonly></h3>
                    <h3>address:<input type="text" value="{{user.address}}" style="color:brown" readonly></h3>
                    <h3>Image:<input type="text" value="{{user.image}}" style="color:brown" readonly></h3>
                    {% endif %}
                </ul>
                <br>
                <br>
                <button type="submit" class="btn btn-primary"><a href="profile_update/" style="color:white;">Update Profile</a> </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}


templates/profile_update.html
{% extends "base.html" %}


{% block content %}
<div class="ui form">
    <div class="container mt-4">
        <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
            <h1 class="display-6" align="center" style="color:teal;"> Profile Update</h1>
            <br>
            <form class="ui form" method="post">
                {% csrf_token %}
                <h3>Name : <input type="text" value="{{user.name}}" name="name" style="color:red" readonly></h3>
                <h3>mobile No : <input type="text" value="{{user.mobileNo}}" name="mobileNo" style="color:red"></h3>
                <h3>email : <input type="text" value="{{user.email}}" name="email" style="color:red"></h3>
                <h3>pwd: <input type="text" value="{{user.pwd}}" name="pwd" style="color:red"></h3>
                <h3>address: <input type="text" value="{{user.address}}" name="address" style="color:red"></h3>
                 <button  type="submit" class="btn btn-primary">Profile up to dated</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}


templates/questions.html
{% extends "base.html" %}

{% block content %}
<div class="ui form" xmlns="http://www.w3.org/1999/html">
    <div class="container mt-4">
        <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
            <h1>Question Page</h1>
            <form action="/office/{{state.workflow.id}}/submit" method="POST">
                <input type="hidden" name="state_id" value={{state.id}}>
                {% for q in state.question_set %}
                <h2><label>{{q.question_text}}</label></h2>
                {% if q.question_type == 1 %}
                <ul>
                    {% for o in q.option_set %}
                    {% if option_id and o.id == option_id %}
                        <h3><input name="response" type="radio" value={{o.id}} checked> &nbsp; {{o.value}}</input></h3>
                    {% else %}
                        <h3><input name="response" type="radio" value={{o.id}}> &nbsp; {{o.value}}</input></h3>
                    {% endif %}
                    {% endfor %}
                </ul>
                {% if state and not state.initial_state %}
                <button class="btn btn-warning"><a href="/state/{{state.id}}/previous/" style="color:black">Previous</a></button>
                {% endif %}
                &nbsp;&nbsp;
                <input type="submit" class="btn btn-primary" value="Submit"/>
                {%else %}
                    {% for o in q.option_set %}
                      <h3><a href="/office/{{state.workflow.id}}/review" style="color:black;">{{o.value}}</a></h3>
                    {% endfor %}
                {%endif %}
                {% endfor %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/review.html
{% extends "base.html" %}

{% block content %}
<div class="ui form" xmlns="http://www.w3.org/1999/html">
    <div class="container mt-4">
        <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
            <h1>Review Page</h1>
            <form>
                <table border="5">
                    <thead>
                    <tr>
                        <th> <h3 style="color:brown;">Question</h3></th>
                        <th> <h3 style="color:brown;">User Response</h3></th>

                    </tr>
                    </thead>
                    {% if state %}
                    {% for res in responses %}
                    <tbody>
                    <tr>
                        <td><h3>{{res.question_text}}</h3></td>
                        <td><h3 style="color:brown;">{{res.answer}}</h3></td>
                    </tr>
                    </tbody>
                    {% endfor %}
                    {% endif %}
                </table>
                <br>
                <br>
                <button class="btn btn-primary"><a href="/office/{{state.workflow.id}}/doctor" style="color:black"><h3>Submit to doctor</h3></a>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}


{% block content %}
<div class="ui form">
    <div class="container mt-4">
        <div class="col-lg-6  col-md-8 mx-auto ui segment p-4">
            <h1 class="display-6" align="center" style="color:teal;"> SignupForm </h1>
            <br>
            <form class="ui form" method="post">
                {% csrf_token %}
                <h3 style="color:tomato;">
                {{ form.as_p }}</h3>
                 <button  type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
